title: racket-sudoku
logo: /promo/smooth-sudoku-preview.png
description: Feature-rich sudoku application coded entirely in a Lisp-based, pure-functional language (Racket ISL).
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
