title: racket-sudoku
logo: /promo/smooth-sudoku-preview.png
description: Playable sudoku client written as a HtDW world program in Racket ISL
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
